//+======================================================================
// $Source:  $
//
// Project:   Tango
//
// Description:  Basic Dialog Class to display info
//
// $Author: pascal_verdier $
//
// Copyright (C) :      2004,2005,2006,2007,2008,2009,2009,2010,2011,2012,2013,2014,2015
//						European Synchrotron Radiation Facility
//                      BP 220, Grenoble 38043
//                      FRANCE
//
// This file is part of Tango.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
// $Revision:  $
//
// $Log:  $
//
//-======================================================================

package org.tango.hdb_configurator.configurator;

import fr.esrf.Tango.DevFailed;
import fr.esrf.tangoatk.widget.util.ATKGraphicsUtils;
import fr.esrf.tangoatk.widget.util.ErrorPane;
import org.tango.hdb_configurator.common.*;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;


//===============================================================
/**
 *	JDialog Class to display info
 *
 *	@author  Pascal Verdier
 */
//===============================================================


public class TTLDialog extends JDialog {

	private JFrame	parent;
	private String nbDayStr = null;
	private List<HdbAttribute> hdbAttributeList;
	private Subscriber subscriber;
	private int returnValue = JOptionPane.OK_OPTION;

	//===============================================================
	/**
	 *	Creates new form TTLDialog
	 */
	//===============================================================
	TTLDialog(JFrame parent, List<HdbAttribute> hdbAttributeList, Subscriber subscriber) throws DevFailed {
		super(parent, true);
		this.parent = parent;
		this.hdbAttributeList = hdbAttributeList;
        this.subscriber = subscriber;
        initComponents();

		//  Get the first TTL found as default
		for (HdbAttribute hdbAttribute : hdbAttributeList) {
		    if (hdbAttribute.getTTL()>0) {
		        nbDayStr = Long.toString(hdbAttribute.getTTL()/24);
                ttlButton.setSelected(true);
                ttlTextField.setText(nbDayStr);
                break;
            }
        }
        //  If nothing found take default one
		if (nbDayStr==null)
            nbDayStr = Long.toString(TangoUtils.getDefaultTTL());


		pack();
 		ATKGraphicsUtils.centerDialog(this);
	}
	//===============================================================
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
	//===============================================================
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        javax.swing.JPanel topPanel = new javax.swing.JPanel();
        javax.swing.JLabel titleLabel = new javax.swing.JLabel();
        javax.swing.JPanel centerPanel = new javax.swing.JPanel();
        ttlButton = new javax.swing.JRadioButton();
        ttlTextField = new javax.swing.JTextField();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JPanel bottomPanel = new javax.swing.JPanel();
        javax.swing.JButton okBtn = new javax.swing.JButton();
        javax.swing.JButton cancelBtn = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Dialog", Font.BOLD, 18)); // NOI18N
        titleLabel.setText("   Attribute Time To Live   ");
        topPanel.add(titleLabel);

        getContentPane().add(topPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setLayout(new java.awt.GridBagLayout());

        ttlButton.setText("Set TTL  ");
        ttlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttlButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 0);
        centerPanel.add(ttlButton, gridBagConstraints);

        ttlTextField.setColumns(4);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        centerPanel.add(ttlTextField, gridBagConstraints);

        jLabel2.setText(" days");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 20);
        centerPanel.add(jLabel2, gridBagConstraints);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });
        bottomPanel.add(okBtn);

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        bottomPanel.add(cancelBtn);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	//===============================================================
	//===============================================================
    @SuppressWarnings("UnusedParameters")
	private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
		long nbDays = getNbDays();
		if (nbDays<0) {
		    ErrorPane.showErrorMessage(this, "NumberFormatException", new Exception("Invalid TTL value"));
		    return;
        }
        try {
            long ttl = nbDays * 24;
            subscriber.setTTL(hdbAttributeList, ttl);
        }
        catch (DevFailed e) {
		    ErrorPane.showErrorMessage(this, e.toString(), e);
        }
        returnValue = JOptionPane.OK_OPTION;
		doClose();
	}//GEN-LAST:event_okBtnActionPerformed
	//===============================================================
	//===============================================================
	@SuppressWarnings("UnusedParameters")
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
		returnValue = JOptionPane.CANCEL_OPTION;
		doClose();
	}//GEN-LAST:event_cancelBtnActionPerformed
	//===============================================================
	//===============================================================
    @SuppressWarnings("UnusedParameters")
	private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
		returnValue = JOptionPane.CANCEL_OPTION;
		doClose();
	}//GEN-LAST:event_closeDialog
	//===============================================================
	//===============================================================
	@SuppressWarnings("UnusedParameters")
	private void ttlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttlButtonActionPerformed
        //  ToDo
        JRadioButton button = (JRadioButton) evt.getSource();
        if (button.isSelected())
        ttlTextField.setText(nbDayStr);
        else {
            //  Get value (as str) for next time
            nbDayStr = ttlTextField.getText();
            ttlTextField.setText("");
        }
        ttlTextField.setEnabled(button.isSelected());
    }//GEN-LAST:event_ttlButtonActionPerformed
    //===============================================================
    //===============================================================
    private long getNbDays() {
        // check if TTL is set
        if (ttlButton.isSelected()) {
            try {
                return Long.parseLong(ttlTextField.getText());
            } catch (NumberFormatException e) {
                return -1;
            }
        }
        else
            return 0;
    }
	//===============================================================
	//===============================================================
	private void doClose() {
	
		if (parent==null)
			System.exit(0);
		else {
			setVisible(false);
			dispose();
		}
	}
	//===============================================================
	//===============================================================
	public int showDialog() {
		setVisible(true);
		return returnValue;
	}

	//===============================================================
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ttlButton;
    private javax.swing.JTextField ttlTextField;
    // End of variables declaration//GEN-END:variables
	//===============================================================




	//===============================================================
	/**
	* @param args the command line arguments
	*/
	//===============================================================
	public static void main(String args[]) {
		try {
            HdbAttribute attribute =
                    new HdbAttribute("tango://orion.esrf.fr:10000/sy/ps-rips/manager/state");
            attribute.setTTL(20*24);
            List<HdbAttribute> attributeList = new ArrayList<>();
            attributeList.add(attribute);
            //  Build subscriber map
            SubscriberMap subscriberMap = new SubscriberMap(Utils.getConfiguratorProxy());
            Subscriber subscriber = subscriberMap.getSubscriberList().get(0);
            new TTLDialog(null, attributeList, subscriber).setVisible(true);
		}
		catch(DevFailed e) {
            ErrorPane.showErrorMessage(new Frame(), null, e);
			System.exit(0);
		}
	}

}
