//+======================================================================
// $Source:  $
//
// Project:   Tango
//
// Description:  Basic Dialog Class to display info
//
// $Author: pascal_verdier $
//
// Copyright (C) :      2004,2005,2006,2007,2008,2009,2009,2010,2011,2012,2013,2014,2015
//						European Synchrotron Radiation Facility
//                      BP 220, Grenoble 38043
//                      FRANCE
//
// This file is part of Tango.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
// $Revision:  $
//
// $Log:  $
//
//-======================================================================

package org.tango.hdb_configurator.configurator.strategy;

import fr.esrf.tangoatk.widget.util.ATKGraphicsUtils;
import org.tango.hdb_configurator.common.Context;
import org.tango.hdb_configurator.common.Strategy;

import javax.swing.*;

//===============================================================
/**
 *	JDialog Class to display get context parameters
 *
 *	@author  Pascal Verdier
 */
//===============================================================
class OneContextDialog extends JDialog {
    private Strategy strategy;
    private Context context;
	private int	returnValue = JOptionPane.OK_OPTION;
	//===============================================================
	/**
	 *	Creates new form OneContextDialog
	 */
	//===============================================================
	OneContextDialog(JDialog parent, Strategy strategy) {
        this(parent, new Context("", "", false), true);
        this.strategy = strategy;
    }
	//===============================================================
	/**
	 *	Creates new form OneContextDialog
	 */
	//===============================================================
	OneContextDialog(JDialog parent, Context context, boolean editName) {
		super(parent, true);
        this.context = context;
		initComponents();
        nameTextField.setText(context.getName());
        nameTextField.setEnabled(editName);
        setDescription(context.getDescription());

		pack();
 		ATKGraphicsUtils.centerDialog(this);
	}

	//===============================================================
	//===============================================================
    private void setDescription(String description) {
        String str = "";
        int start = 0;
        int end;
        while ((end=description.indexOf("\\n", start))>0) {
            str += description.substring(start, end) + "\n";
            start = end+2;
        }
        descriptionTextArea.setText(str + description.substring(start));
    }
	//===============================================================
	//===============================================================
    private String  getDescription() {
        String description = descriptionTextArea.getText().trim();
        String str = "";
        int start = 0;
        int end;
        while ((end=description.indexOf("\n", start))>0) {
            str += description.substring(start, end) + "\\n";
            start = end+1;
        }
        return str + description.substring(start);
    }
	//===============================================================
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
	//===============================================================
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        javax.swing.JPanel centerPanel = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        javax.swing.JPanel bottomPanel = new javax.swing.JPanel();
        javax.swing.JButton okBtn = new javax.swing.JButton();
        javax.swing.JButton cancelBtn = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        centerPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Context Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        centerPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Context Description:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        centerPanel.add(jLabel2, gridBagConstraints);

        nameTextField.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        centerPanel.add(nameTextField, gridBagConstraints);

        descriptionTextArea.setColumns(30);
        descriptionTextArea.setRows(10);
        jScrollPane1.setViewportView(descriptionTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        centerPanel.add(jScrollPane1, gridBagConstraints);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });
        bottomPanel.add(okBtn);

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        bottomPanel.add(cancelBtn);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	//===============================================================
	//===============================================================
    @SuppressWarnings("UnusedParameters")
	private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        String name = nameTextField.getText().trim();
        String desc = getDescription();
        String error = checkName(name);
        if (error==null) {
            context.setName(name);
            context.setDescription(desc);
            returnValue = JOptionPane.OK_OPTION;
            doClose();
        }
        else {
            JOptionPane.showMessageDialog(this,
               error, "Error", JOptionPane.ERROR_MESSAGE);
        }
	}//GEN-LAST:event_okBtnActionPerformed

	//===============================================================
	//===============================================================
    private String checkName(String name) {
        if (name.isEmpty()) {
            return "Invalid name !";
        }
        //  Check if already exixts only if creation
        if (strategy !=null) {
            for (Context context : strategy) {
                if (context.getName().equalsIgnoreCase(name))
                    return name + " already exists";
            }
        }
        return null;
    }
	//===============================================================
	//===============================================================
	@SuppressWarnings("UnusedParameters")
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
		returnValue = JOptionPane.CANCEL_OPTION;
		doClose();
	}//GEN-LAST:event_cancelBtnActionPerformed

	//===============================================================
	//===============================================================
    @SuppressWarnings("UnusedParameters")
	private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
		returnValue = JOptionPane.CANCEL_OPTION;
		doClose();
	}//GEN-LAST:event_closeDialog

	//===============================================================
	/**
	 *	Closes the dialog
	 */
	//===============================================================
	private void doClose() {
        setVisible(false);
        dispose();
	}
	//===============================================================
	//===============================================================
    Context getContext() {
        return context;
    }
	//===============================================================
	//===============================================================
	int showDialog() {
		setVisible(true);
		return returnValue;
	}

	//===============================================================
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables
	//===============================================================
}
